### ISSUE TITLE
Invalid JSON file with precomputed proposals of SharpMask on COCO testfull

### ISSUE THREAD

**Issue by ilija139** [facebookresearch/deepmask#27]
When I process the file downloaded from `https://s3.amazonaws.com/deepmask/boxes/sharpmask-coco-test-full-bbox.tar.gz` I get this error:

```
deep32:deepmask/⇒  python prune_objects_3.py sharpmaskZoom_bbox_coco_testfull.json 0.91
Reading file...
Traceback (most recent call last):
  File "prune_objects_3.py", line 6, in <module>
    data = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 6312834042 (char 6312834041)
```

**Comment by ilija139** [comment]
The problem was the file I had was corrupted, either during download or extracting from the archive. It would have been so much easier if the JSON files were divided into smaller chunks or at multiple objects on a separate line. Is very hard to manage them at the current size.
